export const enum Temperature {
  celcius = "metric",
  farenheit = "imperial",
  kelvin = "",
}
// Generated by https://quicktype.io
export default async function fetchweather(city: string, temperature = Temperature.celcius): Promise<WeatherResultProps> {
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=9864e6963f7642192cb7624dd3540544&units=${temperature}`;
  const res = await fetch(url);
  const data = await res.json();
  if ("message" in data) {
    throw new Error(data.message);
  }
  return data;
}
export interface WeatherResultProps {
  coord: Coord;
  weather: Weather[];
  base: string;
  main: Main;
  visibility: number;
  wind: Wind;
  clouds: Clouds;
  dt: number;
  sys: Sys;
  timezone: number;
  id: number;
  name: string;
  cod: number;
}

export interface Clouds {
  all: number;
}

export interface Coord {
  lon: number;
  lat: number;
}

export interface Main {
  temp: number;
  feels_like: number;
  temp_min: number;
  temp_max: number;
  pressure: number;
  humidity: number;
}

export interface Sys {
  type: number;
  id: number;
  country: string;
  sunrise: number;
  sunset: number;
}

export interface Weather {
  id: number;
  main: string;
  description: string;
  icon: string;
}

export interface Wind {
  speed: number;
  deg: number;
}
